version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Nastya1029384756
      - MYSQL_DATABASE=sellars
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Nastya1029384756
    ports:
      - "3307:3306"
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672